language: python
python:
 - "3.6"

install:
  - pip install -r requirements.txt

script:
  - ./build.py

notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: src
  target-branch: master
  local-dir: public
  fqdn: https://myrhy.me
